windows-exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Compiler l'EXE
        working-directory: iversen_engine
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
          pyinstaller --onedir --windowed --name IversenScientific --icon icon.ico --add-data "frontend;frontend" run_desktop.py

      - uses: actions/upload-artifact@v4
        with:
          name: IversenScientific-windows-exe
          path: iversen_engine/dist/IversenScientific
